class F:
    USER = 'USER'
    ENTRY_ORDERID = 'ENTRY_ORDERID'
    ENTRY_PRICE_INITIAL = 'ENTRY_PRICE_INITIAL'
    ENTRY_COUNT = 'ENTRY_COUNT'
    ENTRY_TYPE = 'ENTRY_TYPE'
    ENTRY_PRICE = 'ENTRY_PRICE'
    ENTRY_TIME = 'ENTRY_TIME'
    RANGE_START = 'RANGE_START'
    RANGE_END = 'RANGE_END'
    SL_POINT = 'SL_POINT'
    ALLOWD = 'ALLOWD'
    TRADED = 'TRADED'
    SESSION = 'SESSION'
    BROKER_NAME = 'BROKER_NAME'
    ENTRY_STATUS = 'ENTRY_STATUS'
    ENTRY_TAG = 'ENTRY_TAG'
    WAIT_PERCENT = 'WAIT_PERCENT'
    
    # EXIT FIELD
    EXIT_ORDERID = 'EXIT_ORDERID'
    EXIT_PRICE_INITIAL = 'EXIT_PRICE_INITIAL'
    EXIT_PRICE = 'EXIT_PRICE'
    EXIT_COUNT = 'EXIT_COUNT'
    EXIT_TYPE = 'EXIT_TYPE'
    EXIT_REASON = 'EXIT_REASON'
    EXIT_TIME = 'EXIT_TIME'
    EXIT_STATUS = 'EXIT_STATUS'
    EXIT_TAG = 'EXIT_TAG'
    EXIT_PERCENT = 'EXIT_PERCENT'
    
    # COMMON FIELDS IN ORDERS
    QTY = 'QTY'
    DIRECTION = 'DIRECTION'
    PRODUCT_TYPE = 'PRODUCT_TYPE'
    PRICE = 'PRICE'
    LOOP_NO = 'LOOP_NO'
    RECORDING = 'RECORDING'
    INDEX = 'INDEX'
    CHARGES = 'CHARGES'
    PL = 'PL'
    FREE_MARGIN = 'FREE_MARGIN'
    DRIFT_PT = 'DRIFT_PT'
    DRIFT_RS = 'DRIFT_RS'
    TRANSACTION_TYPE = 'TRANSACTION_TYPE'
    SEGEMENT = 'SEGEMENT'
    ORDER_TYPE = 'ORDER_TYPE'
    
    OPTION_TYPE = 'OPTION_TYPE'
    CE = 'CE'
    PE = 'PE'
    XX = 'XX'
    V = 'V'
    LTP = 'LTP'
    OI = 'OI'
    
    OPEN = 'OPEN'
    HIGH = 'HIGH'
    LOW = 'LOW'
    CLOSE = 'CLOSE'
    LTP = 'LTP'
    VOLUME = 'VOLUME'
    OI = 'OI'
    
    BUY_AMOUNT = 'BUY_AMOUNT'
    SELL_AMOUNT = 'SELL_AMOUNT'
    FILLED_QTY = 'FILLED_QTY'
    FILLED_BUY_QTY = 'FILLED_BUY_QTY'
    FILLED_SELL_QTY = 'FILLED_SELL_QTY'
    EXPIRY_DATE = 'EXPIRY_DATE'
    STRIKE_PRICE = 'STRIKE_PRICE'
    LOT_SIZE = 'LOT_SIZE'
    CAPITAL = 'CAPITAL'
    
    
    # STRATEGY NAMES
    STRATAGY = 'STRATAGY'
    BASE_STRATAGY = 'BASE_STRATAGY'
    
    FIXED_SL = 'FIXED_SL'
    FS_FIRST = 'FS_FIRST'
    FS_SECOND = 'FS_SECOND'
    FS_THIRD = 'FS_THIRD'
    FS_FOURTH = 'FS_FOURTH'
    FS_FIFTH = 'FS_FIFTH'
    
    RANGE_BREAKOUT = 'RANGE_BREAKOUT'
    RB_FIRST = 'RB_FIRST'
    RB_SECOND = 'RB_SECOND'
    RB_THIRD = 'RB_THIRD'
    RB_FOURTH = 'RB_FOURTH'
    RB_FIFTH = 'RB_FIFTH'
    RB_SIXTH = 'RB_SIXTH'
    
    STBT = 'STBT'
    STBT_FIRST = 'STBT_FIRST'
    STBT_SECOND = 'STBT_SECOND'
    
    BTST = 'BTST'
    BTST_FIRST = 'BTST_FIRST'
    BTST_SECOND = 'BTST_SECOND'
    
    HEDGES = 'HEDGES'
    
    # INDEX
    NIFTY = 'NIFTY'
    BANKNIFTY = 'BANKNIFTY'    
    MIDCPNIFTY = 'MIDCPNIFTY'    
    FINNIFTY = 'FINNIFTY'      
    NIFTYNXT50 = 'NIFTYNXT50'    
    BANKEX = 'BANKEX'
    SENSEX50 = 'SENSEX50'      
    SENSEX = 'SENSEX'
    
    # OTHER
    KOTAK_NEO = 'KOTAK_NEO'
    FLAT_TRADE = 'FLAT_TRADE'
    
    ORDER_STATUS = 'ORDER_STATUS'
    ORDERID = 'ORDERID'
    TICKER = 'TICKER'
    TOKEN = 'TOKEN'
    TAG = 'TAG'
    DTE = 'DTE'
    OPTION_TYPE = 'OPTION_TYPE'
    MESSAGE = 'MESSAGE'
    ORDER_TIME = 'ORDER_TIME'
    
    CONSUMER_KEY = "CONSUMER_KEY"
    SECRETKEY = "SECRETKEY"
    MOBILENUMBER = "MOBILENUMBER"
    LOGIN_PASSWORD = "LOGIN_PASSWORD"
    SESSION_VALIDATION_KEY = "SESSION_VALIDATION_KEY"
    TWO_FACTOR_CODE = "TWO_FACTOR_CODE"

